import { HairPack } from './types';

export const hairPacks: HairPack[] = [
  {
    id: 'intensive-regrowth',
    name: 'Pack Intensive Regrowth',
    tagline: 'Regeneração Capilar Avançada',
    description: 'Tratamento científico intensivo para casos severos de queda e calvície. Fórmula com ativos clinicamente comprovados.',
    benefits: [
      'Reduz queda em até 87% em 3 meses',
      'Estimula crescimento de novos fios',
      'Fortalece raiz e haste capilar',
      'Ativa folículos dormentes',
      'Resultados visíveis em 30 dias',
    ],
    idealFor: [
      'Queda intensa e constante',
      'Entradas e calvície progressiva',
      'Histórico familiar de calvície',
      'Falhas no couro cabeludo',
    ],
    price: 149.90,
    originalPrice: 199.90,
    image: 'https://images.unsplash.com/photo-1556228578-8c89e6adf883?w=600&h=800&fit=crop',
    recommended: true,
    shopifyUrl: '#',
    ingredients: ['Minoxidil 5%', 'Biotina', 'Cafeína', 'Saw Palmetto', 'Niacinamida'],
    results: 'Resultados clínicos em 90 dias',
  },
  {
    id: 'fortify-restore',
    name: 'Pack Fortify & Restore',
    tagline: 'Fortalecimento Profundo',
    description: 'Sistema completo para cabelos fracos, quebradiços e em afinamento. Tecnologia de reconstrução molecular.',
    benefits: [
      'Reduz quebra em até 92%',
      'Aumenta espessura dos fios',
      'Nutre profundamente a raiz',
      'Previne queda futura',
      'Cabelo visivelmente mais denso',
    ],
    idealFor: [
      'Cabelo fraco e quebradiço',
      'Afinamento progressivo dos fios',
      'Queda moderada',
      'Falta de volume e densidade',
    ],
    price: 129.90,
    originalPrice: 169.90,
    image: 'https://images.unsplash.com/photo-1522338242992-e1a54906a8da?w=600&h=800&fit=crop',
    shopifyUrl: '#',
    ingredients: ['Queratina Hidrolisada', 'Colágeno', 'Pantenol', 'Arginina', 'Vitamina E'],
    results: 'Fortalecimento visível em 60 dias',
  },
  {
    id: 'scalp-balance',
    name: 'Pack Scalp Balance',
    tagline: 'Equilíbrio e Saúde Capilar',
    description: 'Tratamento especializado para couro cabeludo sensível, oleoso ou com desequilíbrios. Base saudável para crescimento.',
    benefits: [
      'Regula oleosidade excessiva',
      'Acalma couro cabeludo sensível',
      'Reduz irritação e coceira',
      'Cria ambiente ideal para crescimento',
      'Previne queda por inflamação',
    ],
    idealFor: [
      'Couro cabeludo oleoso ou seco',
      'Sensibilidade e irritação',
      'Queda leve a moderada',
      'Desequilíbrio do pH capilar',
    ],
    price: 109.90,
    originalPrice: 139.90,
    image: 'https://images.unsplash.com/photo-1519699047748-de8e457a634e?w=600&h=800&fit=crop',
    shopifyUrl: '#',
    ingredients: ['Ácido Salicílico', 'Tea Tree Oil', 'Aloe Vera', 'Zinco PCA', 'Mentol'],
    results: 'Equilíbrio restaurado em 45 dias',
  },
  {
    id: 'prevention-care',
    name: 'Pack Prevention Care',
    tagline: 'Prevenção Inteligente',
    description: 'Sistema preventivo para quem nota os primeiros sinais de queda. Ação antecipada para manter cabelo saudável.',
    benefits: [
      'Previne queda antes de agravar',
      'Mantém densidade capilar',
      'Fortalece fios desde a raiz',
      'Protege contra agressões externas',
      'Ideal para manutenção contínua',
    ],
    idealFor: [
      'Queda leve e recente',
      'Prevenção de calvície hereditária',
      'Manutenção pós-tratamento',
      'Primeiros sinais de enfraquecimento',
    ],
    price: 89.90,
    originalPrice: 119.90,
    image: 'https://images.unsplash.com/photo-1535585209827-a15fcdbc4c2d?w=600&h=800&fit=crop',
    shopifyUrl: '#',
    ingredients: ['Biotina', 'Cafeína', 'Ginseng', 'Vitaminas B', 'Antioxidantes'],
    results: 'Prevenção eficaz desde o 1º mês',
  },
];
